language: node_js
node_js:
  - "14"

install:
  - npm install

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/cypress --version

script:
- cypress run --record --key 9b5c67c0-cd08-4632-abda-3b4e46972d1b
